config/routes.rb
PluribusClean::Application.routes.draw do

  get "campaigns/new"

  devise_for :admins
  devise_for :users
  resources :campaigns
  resources :users

  root :to => 'home#index'

  match '/about', to: 'home#about'
  match '/raise', to: 'home#raisefunds'
  match '/tou',  to: 'home#tou'
  match '/privacy',  to: 'home#privacy'
  match '/campaigntest', to: 'home#campaigntest'
  match '/contact_email', :to => 'home#sendmail'
  match '/contact', :to => 'home#contact'
  match '/dashboard', :to => 'home#dashboard'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable  
  attr_accessible :email, :password, :password_confirmation
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  attr_accessible :address, :amountraised, :campaignlength, :datepublished, :description, :fundtarget, :organization, :title, :user_id
end

app/models/static.rb
class Static < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :zipcode, :firstname, :lastname
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :authenticate_user!, only: [:edit, :update]
  before_filter only: [:edit, :update] do
    redirect_to root_path unless current_user.admin?
  end
    
  def new
  end

  def show
    @campaign = Campaign.find(params[:id])
    @sponsor = User.find(@campaign.user_id)
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])
    if @campaign.update_attributes(params[:campaign])
      flash.now[:success] = "Campaign updated"
      render 'edit'
    else
      render 'edit'
    end
  end

  private

    def admin?
      self.admin == true
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def dashboard
    @user = current_user
  end

  def tou
  end

  def privacy
  end

  def raisefunds
  end

  def about
  end

  def contact
    @name = ''
    @email = ''
    @message = ''
  end

  def sendmail
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    if validate(@name, @email, @message)
      ContactForm.contact(@name, @email, @message).deliver
      #if request.xhr?
        flash[:success] = "Message sent successfully"
      #else
      #  flash.now[:error] = "Unkown error ocurred, please try again later"
      #end
      #redirect_to root_path
      redirect_to root_path
    else
      flash.now[:error] = @error
      #redirect_to contact_path + "#flash"
      render 'root'
    end
  end

  private
    def validate(name, email, message)
      @email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      if name.blank? || email.blank? || message.blank?
        @error = "Message not sent: Required information not filled"
        return false
      elsif name.length >= 40
        @error = "Message not sent: Name must be smaller than 40 characters"
        return false
    elsif email[@email_regex].nil?
        @error = "Message not sent: Email not valid"
        return false
      else
        return true
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def signed_in?
    !current_user.nil?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/campaigns/edit.html.erb
<br />
<br />
<br />
<div class="container">
  <div class="row">
    <div class="span6">
      <h1>Update Campaign</h1><br />
      <%= form_for(@campaign) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :fundtarget %>
      <%= f.number_field :fundtarget %>

      <%= f.label :campaignlength %>
      <%= f.number_field :campaignlength %>

      <%= f.label :description %>
      <%= f.text_field :description %><br />

      <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/campaigns/index.html.erb
<h1>TEST PAGE HOMIE!!!!</h1>

app/views/campaigns/new.html.erb
<h1>Campaigns#new</h1>
<p>Find me in app/views/campaigns/new.html.erb</p>

app/views/campaigns/show.html.erb
<br />
<br />
<br />
<div class="cheader">
    <div class="container">
        <div class="row">
            <div class="span11 offset1">
                <div class="cheaderbox">
                    <h2><%= @campaign.title %></h2>
                    <h3>Sponsored by <%= @campaign.organization %></h3></div>
                    <h4><i class="icon-home"></i> Washington, DC</h4><br>
                    <% if user_signed_in? && current_user.admin? %>
                      <%= link_to "Edit Campaign", edit_campaign_path %><br />
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="span1">
            <center>
            <div class="social-tools">
                <span class='st_facebook_vcount' displayText='Facebook'></span>
                <span class='st_twitter_vcount' displayText='Tweet'></span>
                <span class='st_email_vcount' displayText='Email'></span>
            </div>
            </center>
        </div>
        <div class="span7 campaignmiddlebar">
            <div class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#home" data-toggle="tab">Home</a></li>
                    <li><a href="#updates" data-toggle="tab">Updates</a></li>
                    <li><a href="#backers" data-toggle="tab">Backers</a></li>
                    <li><a href="#discussion" data-toggle="tab">Discussion</a></li>
                </ul>
            </div>
            <div class="tab-content">

                <!-- Home -->
                <div class="tab-pane active" id="home">
                    <div class="aboxl">
                        <center><img src="/assets/market.jpg" width="650px"></center>
                    </div>
                    <div class="aboxl">
                        <h3>Project Description</h3>
                        <p>After years of waiting for a major developer to bring a quality grocery and market to this urban neighborhood, local residents are working with a professional produce supplier to create a new fresh market to serve locals high quality food.</p><br />
                        <p>The project sponsor has already negotiated a lease to the storefront and only needs the financial backing to make this dream a reality. Supporters who fund this project will be directly responsible for bringing high quality produce to an underserved part of town, and will get to enjoy a great new market to shop at at the same time!</p><br />
                        <h3>Financial Status of Project</h3>
                        <p>The Project Sponsor has already secured over $100,000 in local investor funds, and has negotiated a line of credit with the local bank, however this is not enough to make this project a reality. In order to be successful, this project will need to raise $100,000 more (for a total of $200,000) in order to successfully purchase new equipment (refrigerators, registers, furnishings), make appropriate lease payments and retain enough working capital for operations.</p><br />
                        <h3>About the Project Sponsor</h3>
                        <p>Brian S. is a talented and socially-motivated entrepreneur. Having spent over 9 years working in management for major grocery retailers, this new market is his dream to delivery a high quality market to his neighborhood. In addition to his expertise in the industry, Brian has also retained Fresh Farms, LLC to provide all the fresh produce on a semi-weekly basis to the Market. Fresh Farms is a leading produce supplier to many DC markets and restaurants.</p><br />
                        <h3>What's Next?</h3>
                        <p>Once the project has been fully funded, Brian will sign the lease paperwork and immediately begin renovating the space for the market.</p><br />
                    </div>
                </div>

                <!-- Updates -->
                <div class="tab-pane" id="updates">
                    <div class="aboxl">
                        <h3>Updates</h3>
                        <p><i>No updates yet, please check back later.</i></p><br />
                    </div>
                </div>

                <!-- Backers -->
                <div class="tab-pane" id="backers">
                    <div class="aboxl">
                        <h3>Backers</h3>
                        <p><strong>John S</strong> made a $50 donation</p>
                        <p><strong>Isabel F</strong> made a $150 donation</p>
                        <p><strong>Teresa S</strong> made a $20 donation</p>
                        <p><strong>Grant H</strong> made a $10 donation</p>
                        <p><strong>Irvin W</strong> made a $150 donation</p>
                        <p><strong>Heidi P</strong> made a $50 donation</p>
                        <p><strong>Ella V</strong> made a $50 donation</p>
                        <p><strong>Aiden T</strong> made a $1050 donation</p>
                        <p><strong>Ali S</strong> made a $150 donation</p>
                        <p><strong>Gwen B</strong> made a $10 donation</p>
                        <p><strong>Moises S</strong> made a $150 donation</p>
                        <p><strong>Crystal B</strong> made a $20 donation</p>
                        <p><strong>Shonda M</strong> made a $20 donation</p>
                        <p><strong>Amir R</strong> made a $150 donation</p>
                        <p><strong>Darren Q</strong> made a $150 donation</p>
                        <p><strong>Kiersten N</strong> made a $50 donation</p>
                        <p><strong>Alex A</strong> made a $10 donation</p>
                        <p><strong>Omar B</strong> made a $50 donation</p>
                        <p><strong>Amir R</strong> made a $20 donation</p>
                        <p><strong>Carolina W</strong> made a $150 donation</p>
                        <p><strong>John S</strong> made a $50 donation</p>
                    </div>
                </div>

                <!-- Discussion -->
                <div class="tab-pane" id="discussion">
                  <div class="aboxl">
                    <h3>Discussion</h3>
                    <p><i>No discussions yet, please check back later.</i></p><br />
                    <h2>
                      Address: <%= @campaign.address %><br />
                      Campaign Length: <%= @campaign.campaignlength %> days<br />
                      Amount Raised: <%= @campaign.amountraised %><br />
                      Campaign Target: <%= @campaign.fundtarget %><br />
                    </h2>
                    <h3>
                      Description:<br />
                    </h3>
                    <p> <%= @campaign.description %></p>
                  </div>
                </div>
            </div>
        </div>
        <div class="span4 campaignrightbar">
                <div class="aboxr">
                    <strong><h4>Amount Raised: <%= number_to_currency(@campaign.amountraised, precision: 0) %></h4></strong>
                    <div class="progress">
                        <% @percentcomplete = @campaign.amountraised.to_f / @campaign.fundtarget.to_f * 100 %>
                        <div class="bar bar-success" style="width: <%= number_to_percentage(@percentcomplete, precision: 0) %>;"></div>
                    </div>
                    <h4>Out of: <%= number_to_currency(@campaign.fundtarget, precision: 0) %> goal</h4>
                    <h4>Total Contributors: 776</h4>
                    <center><%= link_to "Contribute Funds Now!", root_path, :class => "btn btn-custom .btn-large" %></center>
                </div>
                <div class="ownerbox">
                    <p>Campaign started by <strong><%= @sponsor.firstname %></strong> of <strong>Washington, DC</strong></p>
                </div>
                <div class="perkbox">
                    <h4>$10 Donation</h4>
                    <p>Once fully operational, the New Market will donate one lunch on your behalf to the local school</p>
                </div>
                <div class="perkbox">
                    <h4>$20 Donation</h4>
                    <p>Be invited to our opening day as one of the first customers and receive a custom-made reusable grocery bag made exclusively for project backers</p>
                </div>
                <div class="perkbox">
                    <h4>$50 Donation</h4>
                    <p>Receive everything from lower sponsorship levels, and also have your name placed in the announcement newsletter as a backer of the new market</p>
                </div>
                <div class="perkbox">
                    <h4>$150 Donation</h4>
                    <p>Receive everything above, and once the Market opens we will deliver a crate of the best local seasonal fruits and vegetables to your door.</p>
                </div>
        </div>
    </div>
</div>

app/views/contact_form/contact.text.erb
From: <%= @name %> (<%= @email %>)
on <%= @sent_at %>

Message:
==================================================================
<%= @message %>
==================================================================

app/views/home/_contact_form.html.erb
<%= form_tag(contact_email_path, :method => 'post') do %>
  <%= label_tag "Your Name:" %>
  <%= text_field_tag "name", @name %>
  <%= label_tag "Email:" %>
  <%= text_field_tag "email", @email %>
  <%= label_tag "Message:" %>
  <%= text_area_tag "message", @message, :rows => "5", :style => "width: 450px;" %>
  <div class="action">
    <%= submit_tag "Send" %>
  </div>
<% end %>

app/views/home/about.html.erb
<br />
<br />
<br />
<br />
<div class="container">
  <h2>About PluribusFund</h2>
  <br />
  <p>PluribusFund is a Crowdfunding Portal designed to fund investments in local projects that strengthen and enrich our local communities. In addition to serving as a funding portal, Pluribus serves as a platform to connect individuals with local organizations , businesses, social causes and creative projects in their community.</p><br />
  <h3>What is Crowdfunding?</h3>  
  <p>Crowdfunding is the collective effort of many individuals pooling their money (in this case via a website) to support the efforts of other people or organizations. In theory, this can be applied to almost any project whether it be an art project, a new business, community-development, a new invention, etc.</p><br />
  <h3>Why Community-Funding?</h3>
  <p>Other crowdfunding sites have served as a terrific source of funding for many worthy creative projects, but the majority of projects hosted on these sites unfortunately do not raise the desired funds and when they do are often unaccountable for results. Community-based crowdfunding serves to mitigate these challenges in two important ways:</p>
  <ul>
    <li>Tapping in to existing community networks: Pluribus empowers projects to tap into local communities and social networks and then build upon these networks to expand their reach beyond these groups through the Pluribus Crowdfunding Portal.</li>
    <li>Community Involvement: Projects funded by Pluribus give local funders the opportunity to meet project sponsors directly through events such as town-hall meetings or project kick-offs. By gaining the opportunity to meet and discuss the proposed projects with their sponsors can help ensure that the funder's investment is being appropriately used.</li>
  </ul><br />
  <h3>How to Get Involved</h3>
  <ul>
    <li>Start a Campaign: We are looking for high quality campaigns that will fund new exciting projects, organizations and businesses in the area. Think you've got a good idea? Contact us so we can work with you to get your project posted and raising funds.</li>
    <li>Get Involved: Looking to get involved in an existing project? Projects not only need funds, but also skills such as programming, legal, engineering, and marketing among many, many others. For all of our projects, you can contact the project organizer directly to get involved any way you can to make these projects a success.</li>
  </ul><br />
  <h3>Map of Sample Projects</h3>
  <p>We believe that the possibilities for community-based crowdfunding are as diverse as the communities in which we live. From projects as diverse as the arts, real estate investment, small business, charity and non-profits, Pluribus aims to be a vehicle for investing in all aspects of our communities</p><br />
  <h4>Click on the icons in the map below to see some of the many project ideas we hope to fund in the future:</h4>
  <br />
  <center>
    <%= gmaps( :kml => {:data => '[{ url: "http://bramira.com/kdata.kml"}]'}, 
      :map_options => {"center_latitude" => 0, "center_longitude" => 180, "auto_adjust" => true, :raw => '{ disableDefaultUI: true, scrollwheel: false }'}
      ) %> 
    </center><br /><br />
  </div>

app/views/home/contact.html.erb
<div id="aboutus">
  <div class="container">
    <div class="row">
      <div class="span7">
        <h2>Contact Us</h2>
        <p>Thank you for your interest in PluribusFund! We are excited to start funding local projects, organizations and businesses and hope you will check back frequently for new updates.</p><br />
        <p>If you would like to get ahold of us, please feel free to email us at anytime at: <strong>info (at) pluribusfund.com</strong></p>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
      </div>
    </div>
  </div>
</div>

app/views/home/dashboard.html.erb
<div id="aboutus">
  <div class="container">
    <div class="row">
      <div class="span7">
        <h3>Dashboard for <%= @user.firstname %> <%= @user.lastname %></h3>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="customtitlebar">
    <div id="customtitlebarcontent">
        <h1>PluribusFund is a crowdfunding platform designed to serve and build local DC Metro area communities</h1>
        <%= link_to "Learn More", about_path, :class => "btn" %>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="span4 tribar">
            <h2>Local</h2>
            <i class="icon-star"></i> <i class="icon-star"></i> <i class="icon-star"></i><br /><br />
            <p style="font-size: 16px;">Our goal is to direct crowdfunded investment into local businesses, non-profits, community groups, religious institutions and creative projects – allowing DC area citizens to make a direct impact on their communities.</p>
        </div>
        <div class="span4 tribar">
            <h2>Community-Based</h2>
            <i class="icon-home" style="font-size: 60px;"></i>
            <p style="font-size: 16px;">PluribusFund seeks to empower existing community networks to fund local initiatives that will strengthen and improve the quality of life for local funders.</p>
        </div>
        <div class="span4 tribar">
            <h2>Social</h2>
            <i class="icon-share" style="font-size: 60px;"></i>
            <p style="font-size: 16px;">By facilitating social involvement and interaction between funders and funded, PluribusFund works to increase trust and transparency through both online and in-person interaction with recipient organizations.</p>
        </div>
    </div>
</div>
<div id="features">
    <div class="container">
        <!-- <div class="section_header">
            <h2>All About Pluribus</h2>
        </div> --> 
        <!-- <div class="row feature">
            <div class="span6">
                <img src="assets/local.jpg" />
            </div>
            <div class="span6 info">
                <h3>
                    <center>Local Projects, Local Funding</center>
                </h3>
                <p style="font-size: 17px; text-align: justify; word-spacing: 4px;">
                    Whether it be community-service, food, culture, arts, education or business, Pluribus is dedicated to connecting local residents with high quality organizations in their community. By directing investment locally, citizens can make a direct impact on the communities in which they live.
                </p>
            </div>
        </div> -->
        <div class="row feature ss">
            <div class="span6 info">
                <h3>
                    <center>Built Upon Trust</center>
                </h3>
                <p style="font-size: 17px; text-align: justify; word-spacing: 4px; padding-left: 60px;">
                    To protect funders' donations and investments, all organizations seeking funds through Pluribus will be subject to our due diligence process. Our due diligence process includes background information on project leadership, organization history and a credible plan what the funds will be used for. Any campaign not able to provide this information will never be hosted here. In addition to protecting funders' investments, this process is designed to enhance the credibility and trust given to all projects hosted by PluribusFund to maximize funding.
                </p><br /><br />
            </div>
            <div class="span6" style="text-align: center;">
                <img src="assets/process.png"/>
            </div>
        </div>
    </div>
</div>

app/views/home/raise.html.erb
<br />
<br />
<br />
<br />
<div class="container">
  <h2>Interested in Raising Funds?</h2>
  <p>Pluribus is currently working with several organizations to roll out its inaugural class of fund-raising campaigns in the DC Metro Area. If you are interested...</p><br />
</div>

app/views/home/raisefunds.html.erb
<div id="aboutus">
  <div class="container">
    <h2>Interested in Raising Funds?</h2><br />
    <div class="row">
      <div class="span9 intro">
        <p style="font-size: 17px; word-spacing: 3px;">PluribusFund is looking to partner with high-quality organizations to develop and ultimately fund exciting projects, organizations and businesses in the DC area. If you feel that you have a great idea for a project and would be interested in partnering with PluribusFund to help fund your idea, we would like to hear from you!</p><br />
        <p style="font-size: 17px; word-spacing: 3px;">Please send us an note using the form below with a brief description of your project and we will do our best to respond within 24 hours:</p><br />
        <%= render 'home/contact_form' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer">
    <div class="container">
        <div class="row sections">
            <div class="span4 recent_posts">
                <h3 class="footer_header">
                    Quick Links
                </h3>
                <div class="post" style="margin-left: 25px;">
                    <%= link_to('About', about_path, :class => "title") %>
                    <%= link_to('Contact', contact_path, :class => "title") %>
                    <a href="../campaigntest" class="title">Example Campaign</a>
                    <a href="privacy" class="title">Privacy Policy</a>
                    <a href="../raise" class="title">Raise Funds</a>
                    <%= link_to('Sign Up', new_user_registration_path, :class => "title")  %>
                    <a href="tou" class="title">Terms of Use</a>
                </div>
            </div>
            <div class="span4 contact">
                <h3 class="footer_header" style="text-align: center;">
                    Join Our Mailing List
                </h3>
                <%= form_tag(contact_email_path, :method => 'post') do %>
                  <%= text_field_tag "name", @name, :placeholder => "Your name" %>
                  <%= text_field_tag "email", @email, :placeholder => "Your email" %>
                  <%= text_area_tag "message", @message, :placeholder => "Message", :rows => "3" %>
                  <div class="action">
                    <%= submit_tag "Send" %>
                  </div>
                <% end %>
            </div>
            <div class="span4 testimonials">
                <h3 class="footer_header">
                    Social Media
                </h3>
                <div class="wrapper">
                    <div class="fb-like" data-href="http://www.pluribusfund.com/" data-send="true" data-width="300" data-show-faces="true" data-font="arial" data-colorscheme="dark"></div>
                    <a href="https://twitter.com/pluribusfund" class="twitter-follow-button" data-show-count="false">Follow @pluribusfund</a>
                </div>
            </div>
        </div>
        
        <div class="row credits">
            <div class="span12">
                <!--
                <div class="row social">
                    <div class="span12">
                        <a href="#" class="facebook">
                            <span class="socialicons ico1"></span>
                            <span class="socialicons_h ico1h"></span>
                        </a>
                        <a href="#" class="twitter">
                            <span class="socialicons ico2"></span>
                            <span class="socialicons_h ico2h"></span>
                        </a>
                        <a href="#" class="gplus">
                            <span class="socialicons ico3"></span>
                            <span class="socialicons_h ico3h"></span>
                        </a>
                    </div>
                </div> -->
                <div class="row copyright">
                    <div class="span12">
                        © 2013 Pluribus Crowdfunding, LLC
                    </div>
                </div>
            </div>            
        </div>
    </div>
</footer>
<%= yield :scripts %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">
            <strong>PLURIBUSFUND</strong>
        </a>
        <div class="nav-collapse collapse">
            <ul class="nav pull-right">
                <li><%= link_to('About', about_path) %></li>
                <li><a href="/campaigntest">Example Campaign</a></li>
                <li><a href="/raise">Raise Funds</a></li>
                <% if user_signed_in? %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            My Account
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to('Account Dashboard', dashboard_path, :method => :post) %></li>
                            <li><%= link_to('Edit Account Details', edit_user_registration_path(@user), :method => :get) %></li>
                            <li><%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %></li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to('Sign Up', new_user_registration_path)  %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Sign In
                            <b class="caret"></b>
                        </a>
                        <div class="dropdown-menu" style="padding: 10px;">
                            <%= form_for("user", :url => user_session_path) do |f| %>
                              <div><%= f.email_field :email, :placeholder => "email address", :autofocus => true %></div>
                              <div><%= f.password_field :password, :placeholder => "password" %></div>
                              <div><%= f.submit "Sign in" %></div>
                            <% end %>
                        </div>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Pluribus Crowdfunding</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <script type="text/javascript">var switchTo5x=true;</script>
    <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
    <script type="text/javascript">stLight.options({publisher: "e91fb82b-5ba3-4539-97f4-fc40fd12ca3d", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
    
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
    <% if Rails.env == "production" %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-44274700-1', 'pluribusfund.com');
      ga('send', 'pageview');

    </script>
    <% end %>
</head>
<body class="pull_top">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

    <%= render 'layouts/navbar' %>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
</body>
</html>